# ---
# - name: Install Nginx
#   hosts: all
#   become: true
#   tasks:
#     - name: Install Nginx package
#       apt:
#         update_cache: yes
#     - name: nginx
#       apt:
#         name: nginx
#         state: present
#     - name: Start Nginx service
#       service:
#         name: nginx
#         state: started
#         enabled: yes
#   vars:
#     ansible_ssh_private_key_file: /home/runner/.ssh/id_rsa
---
- name: Install Nginx
  hosts: all
  become: true
  
  tasks:
  - name: Install Nginx package
    apt:
      name: nginx
      state: present
      # update_cache: yes

  # - name: Check status of service
  #   shell: systemctl status nginx

  - name: Start Nginx service
    service:
      name: nginx
      state: started
      enabled: yes
