---
- name: Copy SSH Key to Managed Nodes
  hosts: all # Use the appropriate group or hostname from your inventory file
  become: yes # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Copy SSH Key
      authorized_key:
        user: "{{ ansible_user }}" 
        key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}" 
