# .github/workflows/main.yml

name: Install Nginx

on:
  push:
    branches:
      - main

jobs:
  install-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Create SSH Key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key

      - name: Run Ansible Playbook
        run: ansible-playbook install_nginx.yml -i /etc/ansible/hosts --private-key=ssh_key
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
